services:
  broker:
    image: docker.io/library/redis:8
    userns_mode: "keep-id"
    container_name: paperless-broker
    volumes:
      - paperless_redis:/data
    restart: unless-stopped

  paperless-ngx:
    image: ghcr.io/podmania/paperless-ngx:latest
    userns_mode: "keep-id"
    container_name: paperless-ngx
    ports:
      - 8000:8000
    volumes:
      - ./data:/usr/src/paperless/data
      - ./media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
      - /etc/localtime:/etc/localtime:ro
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBENGINE: sqlite
    restart: unless-stopped
volumes:
  paperless_redis:
